### ISSUE TITLE
vdr-plugin-vnsiserver

### ISSUE THREAD

**Issue by S-V-S** [OpenMediaVault-Plugin-Developers/openmediavault-vdr#10]
Add vdr-plugin-vnsiserver. Enables control of VDR through XBMC.
How to setup?
0.5.6 or wait for OMV 0.6?

**Comment by nohatssir** [comment]
This has been fixed with the introduction of an openmediavault-vdr-vnsiserver plugin for openmediavault-vdr 3.0.1.
