### ISSUE TITLE
bug: Recording directory privileges not updated properly

### ISSUE THREAD

**Issue by S-V-S** [OpenMediaVault-Plugin-Developers/openmediavault-vdr#17]
VDR does not start. 
runvdr: stopping after fatal fail (vdr: can't access video directory /media... )
Plugin v3.0.4
OMV v3.0.26

**Comment by nohatssir** [comment]
Plugins doesn't handle permissions on shared folders. I added a warning for incorrect permissions to help users here 08c362286195de4179fcf04f0c89d7bcd0cb5660.

**Comment by S-V-S** [comment]
> Plugins doesn't handle permissions on shared folders.
Why not? Plugins used to handle the permissions so why is it changed?

**Comment by nohatssir** [comment]
No, not really. Only the plugins that utilized mntentrefs managed permissions. It's a bad idea to let plugins manage permissions on shared folders since the plugin then can screw up permissions that users have set themselves.

**Comment by S-V-S** [comment]
The plugin used to handle ACL for the vdr user to access the recording directory.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-vdr/blob/0.5/usr/share/openmediavault/mkconf/vdr#L49-L52

The enduser cannot even see the system account "vdr" with the "show privileges" button next to the recording directory dropdown. Instead he has to go to the /SharedFolders/SelectFolder/SetACL/.
I really think the old way should be used. Having to set the same thing twice is not user-friendly.

**Comment by nohatssir** [comment]
You don't set it twice, you set it once. And why would you set it in the privileges window when that window doesn't touch filesystem permissions at all?

**Comment by S-V-S** [comment]
If I set my vdr recording directory as Shared Folder X of course I also want vdr to have the correct privileges to that folder. Hopefully with the latest commit there won't be so much people asking for help on the forum.

I meant the privileges button in the image below. I thought it was added for this plugin but It seems to be in the OMV base system and it's good for managing who has access to the directory.

![privileges_button](https://cloud.githubusercontent.com/assets/6023608/16926168/4ab6d4f6-4d30-11e6-946e-e6b775402cab.png)

**Comment by nohatssir** [comment]
I can't really remember the last time anyone asked for help with VDR and permissions was the issue though, and there shouldn't hopefully be any in the future either. :)

That 'Show privileges' button only affects access to Samba shares, not filesystem access. It even says that in the yellow area with text in the window that pops up.
