### ISSUE TITLE
Add "EPG Scan Timeout" to parameters

### ISSUE THREAD

**Issue by S-V-S** [OpenMediaVault-Plugin-Developers/openmediavault-vdr#18]
We should add EPG Scan Timeout to parameters with a default value of 1.
Some people might not have their NAS on for 5 hours every day so EPG will not update unless channels are changed.
Parameter is set in `setup.conf` by `EPGScanTimeout = 1`

From the vdr manual:

> EPG scan timeout 	Default value:5
> The time (in hours) of user inactivity after which the DVB card in a single card system starts scanning channels to keep the EPG up-to-date. A value of '0' completely turns off scanning on both single and multiple card systems.

**Comment by nohatssir** [comment]
Correct me if I'm wrong, but wouldn't the EPG get updated when starting VDR after a boot? It seems awfully weird if you have to update the EPG more often than every fifth hour.

Please don't forget that there's an extra options textarea just for these unique cases. Adding an option for everything is not always the right way to go.

**Comment by S-V-S** [comment]
In OMV 3 after booting vdr starts with channel number 1 active. If I don't change channels then the EPG does not update on the other frequencies. It updates the EPG after the `EPGScanTimeout` has passed. I'm using DVB-C with a single tuner.
This cannot be assigned as a startup parameter. It has to be changed in `setup.conf`
Please reopen this.
